version: "2"

services:
  
  ###############################################
  ## Nginx
  
  nginx:
    image: nginx:1.11
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
    ports:
      - 80
    links: 
      - php
    volumes:
      - ./Build/Docker/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/var/www/Web

  ###############################################
  ## PHP

  php:
    image: php:7-fpm
    env_file:
      - ./.env
    links:
      - mysql
    volumes:
      - ./Build/Docker/php-fpm-pool.conf:/etc/php/7.0/fpm/pool.d/www.conf        
      - ./data:/var/www/Web

  ###############################################
  ## MySQL

  mysql:
    image: mysql:5.6
    env_file:
      - ./.env
    volumes:      
      - ./Build/Docker/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf

  ###############################################
  ## Composer
  
  composer:
    image: composer/composer:1.1
    env_file:
      - ./.env
    working_dir: /app/
    volumes:
      - ./data:/app/
      - ~/.composer/:/composer/   

  ###############################################
  ## NodeJs

  nodejs:    
    image: dragonmantank/nodejs-grunt-bower
    volumes:
      - ./data:/data
      - "~/.gitconfig:/data/.gitconfig"            

  ###############################################
  ## beanstalkd 
  
  #beanstalkd:
  #  image: schickling/beanstalkd
  #  ports:
  #    - 11300:11300

  ###############################################
  ## Mailcatcher

  # mailcatcher:
  #  image: schickling/mailcatcher
  #  environment:
  #    VIRTUAL_HOST: "mailcatcher.${HOSTNAME}"
  #    VIRTUAL_PORT: 1080

  ###############################################
  ## Elasticsearch
  
  # elastic:
  #  image: elasticsearch:1.7
  #  command: elasticsearch -Des.network.host=0.0.0.0
  #  environment:
  #    VIRTUAL_HOST: elastic.${HOSTNAME}
  #    VIRTUAL_PORT: 9200
  #  volumes:
  #    - ./Build/docker/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml  

  ###############################################
  ## Redis
  
  #redis:
  #  image: redis